spring:
  application:
    name: springcloud-service-web-ribbon
  boot:
    admin:
      client:
        url: http://localhost:8084


server:
  port: 8764


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
