
spring:
  application:
    name: springcloud-service-admin


server:
  port: 8763


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
