spring:
  application:
    name: springcloud-service-web-feign
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084


server:
  port: 8765


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

